#!/bin/bash
echo "ALX"
^c
root@9552860cda07:/alx-pre_course/alx-pre_course/0x01-git/bash#
cat > alx
root@9552860cda07:/alx-pre_course/alx-pre_course/0x01-git/bash#ls
root@9552860cda07:/alx-pre_course/alx-pre_course/0x01-git/bash# cd c
clear
